apiVersion: v1
kind: Service
metadata:
  name: greengrub-service
  labels:
    app: greengrub
spec:
  selector:
    app: greengrub
  ports:
    - port: 8080        # Exposed inside cluster
      targetPort: 8080  # Container port
      nodePort: 30080   # External port (optional: you can remove to let K8s pick automatically)
  type: NodePort
